"""
Tests for issue #107: Build Training Log page shell with week navigation and filters
Runs against UAT environment (http://localhost:9001)
"""
import os
import re
from datetime import datetime, timedelta, date as _date

import httpx
import pytest


BASE = os.environ.get("UAT_BASE_URL") or f"http://localhost:{os.environ.get('UAT_PORT', '9001')}"
if not BASE.startswith("http"):
    raise RuntimeError(
        "UAT_BASE_URL / UAT_PORT not set. Run the tester skill's Step 0 to resolve UAT before pytest."
    )

ALICE_USER_ID = "2898f7d7-e2f9-4125-871d-cc4fd5cb40ff"


@pytest.fixture(scope="module")
def client():
    with httpx.Client(base_url=BASE, timeout=10) as c:
        yield c


# ── AC 1: /log and /log.html both return HTTP 200 ─────────────────────────────

def test_training_log_page_shell__get_log_route(client):
    """AC: /log returns HTTP 200 with Training Log page"""
    res = client.get("/log")
    assert res.status_code == 200, f"GET /log failed: {res.status_code}"
    assert "Training log" in res.text, "Page should contain 'Training log' title"


def test_training_log_page_shell__get_log_html_route(client):
    """AC: /log.html returns HTTP 200 with Training Log page"""
    res = client.get("/log.html")
    assert res.status_code == 200, f"GET /log.html failed: {res.status_code}"
    assert "Training log" in res.text, "Page should contain 'Training log' title"


# ── AC 2: Page header displays Log button ─

def test_training_log_page_shell__page_header_elements(client):
    """AC: Page header displays Log button and training sub-tabs"""
    res = client.get("/log")
    assert res.status_code == 200
    
    assert 'id="log-new-btn"' in res.text, "Log button with id='log-new-btn' should exist"
    assert 'id="training-sub-tabs"' in res.text, "Training sub-tabs should exist"



# ── AC 3: Week strip shows 7 day pills ────────────────────────────────────────

def test_training_log_page_shell__week_strip_seven_pills(client):
    """AC: Week strip displays 7 day pills (Mon–Sun) for current week"""
    res = client.get("/log")
    assert res.status_code == 200

    # Day pills are dynamically generated by JS; verify structure is in place
    assert 'week-pills' in res.text, "Week pills container should exist"
    assert 'id="week-pills"' in res.text, "Week pills container with proper ID should exist"

    # Verify training-log.js is loaded (which defines day labels)
    assert 'training-log.js' in res.text, "training-log.js should be loaded for week strip functionality"


def test_training_log_page_shell__week_strip_today_highlight(client):
    """AC: Today's pill is visually highlighted on initial load"""
    res = client.get("/log")
    assert res.status_code == 200

    # Check for today class on a day pill
    assert 'day-pill today' in res.text or '.today' in res.text, \
        "Today's pill should have 'today' class for styling"


# ── AC 4: Week navigation chevrons work ───────────────────────────────────────

def test_training_log_page_shell__week_nav_buttons_present(client):
    """AC: Left and right chevron buttons change displayed week"""
    res = client.get("/log")
    assert res.status_code == 200

    # Look for navigation buttons
    assert 'week-nav-btn' in res.text, "Week navigation buttons should be present"


# ── AC 5: Filter bar exists with search, type chips, date range ────────────────

def test_training_log_page_shell__filter_bar_components(client):
    """AC: Filter bar includes search input, type chips, and date-range chip"""
    res = client.get("/log")
    assert res.status_code == 200

    # Check for search input
    assert 'search' in res.text.lower(), "Search input should exist in filter bar"
    
    # Check for type chips
    for chip_type in ['All', 'Run', 'Lift', 'WOD', 'Bike']:
        assert chip_type in res.text, f"Filter type chip '{chip_type}' should be present"
    
    # Check for date range (30d default)
    assert '30d' in res.text or 'date-range' in res.text, \
        "Date range filter defaulting to 30d should be present"


# ── AC 6: Query params update and persist ─────────────────────────────────────

def test_training_log_page_shell__query_params_type_persists(client):
    """AC: Selecting a type filter updates URL with ?types=<type> and pre-selects on reload"""
    res = client.get("/log?types=run")
    assert res.status_code == 200
    
    # Page should load successfully with query params
    assert 'Training log' in res.text


def test_training_log_page_shell__query_params_range_persists(client):
    """AC: Selecting a date range updates URL and pre-selects on reload"""
    res = client.get("/log?range=14d")
    assert res.status_code == 200
    
    assert 'Training log' in res.text


def test_training_log_page_shell__multiple_query_params(client):
    """AC: Multiple query params work together"""
    res = client.get("/log?types=lift&range=7d")
    assert res.status_code == 200
    
    assert 'Training log' in res.text


# ── AC 7: JavaScript file is present ──────────────────────────────────────────

def test_training_log_page_shell__training_log_js_referenced(client):
    """AC: training-log.js is included in the page"""
    res = client.get("/log")
    assert res.status_code == 200

    assert 'training-log.js' in res.text, "training-log.js should be referenced in page"


def test_training_log_page_shell__training_log_js_valid(client):
    """AC: training-log.js is vanilla JS and fetches from /api/training-log"""
    res = client.get("/js/training-log.js")
    assert res.status_code == 200

    content = res.text
    # Verify it's vanilla JS (no React, Vue, etc.) and contains async/fetch calls for API
    assert ('React' not in content and 'Vue' not in content), "Should be vanilla JS, not framework-based"
    # Check for async/await and fetch which indicate API calls
    assert ('async' in content or 'fetch' in content), "Should contain async/fetch for API calls"


# ── AC 8: API endpoint /api/training-log works ──────────────────────────────────

def test_training_log_page_shell__api_training_log_endpoint(client):
    """AC: /api/training-log endpoint returns data for user"""
    res = client.get(f"/api/training-log?user_id={ALICE_USER_ID}")
    assert res.status_code == 200, f"GET /api/training-log should return 200, got {res.status_code}"
    
    data = res.json()
    assert isinstance(data, dict), "API should return JSON object"


# ── AC 9: Mobile responsive (380 px viewport) ─────────────────────────────────

def test_training_log_page_shell__responsive_meta_viewport(client):
    """AC: Page includes viewport meta tag for 380px responsive design"""
    res = client.get("/log")
    assert res.status_code == 200

    assert 'viewport' in res.text, "Page should have viewport meta tag"
    assert 'width=device-width' in res.text, "Viewport should allow device-width scaling"


# ── AC 10: No console errors ──────────────────────────────────────────────────

def test_training_log_page_shell__no_js_errors(client):
    """AC: No console errors on initial page load"""
    # Fetch the JS file and verify it's syntactically valid
    res = client.get("/js/training-log.js")
    assert res.status_code == 200

    content = res.text
    # Check for common JS syntax issues
    assert '(function' in content or 'function' in content, "Should be valid JS"


# ── UAT Step validation ──────────────────────────────────────────────────────

def test_training_log_page_shell__uat_step_1_page_loads(client):
    """UAT Step 1: Navigate to /log and verify page loads"""
    res = client.get("/log")
    assert res.status_code == 200
    assert 'Training log' in res.text
    assert 'id="log-new-btn"' in res.text


def test_training_log_page_shell__uat_step_2_week_strip(client):
    """UAT Step 2: Week strip shows 7 day pills with today highlighted"""
    res = client.get("/log")
    assert res.status_code == 200
    assert 'day-pill' in res.text
    assert 'today' in res.text


def test_training_log_page_shell__uat_step_5_type_filtering(client):
    """UAT Step 5: Type filter chips present and functional"""
    res = client.get("/log")
    assert res.status_code == 200
    
    # All filter chips should be present
    for chip in ['All', 'Run', 'Lift', 'WOD', 'Bike']:
        assert chip in res.text, f"Filter chip '{chip}' should be present"


def test_training_log_page_shell__uat_step_8_url_persistence(client):
    """UAT Step 8: URL query params persist when reloaded"""
    # Load with specific params
    res = client.get("/log?types=run&range=30d")
    assert res.status_code == 200
    
    # Page should load successfully and be able to handle these params
    assert 'Training log' in res.text


def test_training_log_page_shell__uat_step_9_mobile_layout(client):
    """UAT Step 9: Page has mobile-responsive layout support"""
    res = client.get("/log")
    assert res.status_code == 200
    
    # Check for responsive design elements
    assert 'viewport' in res.text
    assert 'device-width' in res.text


def test_training_log_page_shell__uat_step_10_console_clean(client):
    """UAT Step 10: No console errors on page load"""
    res = client.get("/log")
    assert res.status_code == 200
    
    # Verify page structure is intact (no obvious missing elements)
    assert 'training-log.js' in res.text
    assert 'css/styles.css' in res.text or 'css/' in res.text
